sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: make travis-install
script: make travis-script
after_success: codeclimate-test-reporter
notifications:
  slack:
    secure: WuKrRQ5mNe2NgMV8OrPnU9hvUaY+verV5Avoq2sJ/Lex/ZXr8QtDKT4lw0DDuVyo5548i23Vhjzt1Q5c/v/R/F4rIZccjqzJ0EXPg59/dIT55AfgtQGa0OquSt22ebPPpHOqOnJliGiSAFzYd6tGr0AK/9T0dD4uxadngqEAsLPyHoVjGIIXAjrtPDPPO6oPw00HPsjgc26UBwwz1uNgdutohaIzk6BG/xWC1u0DvkIpP++PRasWN2S2c5cEyrpVCjsXt55P7yddqfNKX+Za/mIwUZ2xmZY5bePT3k4H2EDowR4pdayiTl/ueoGodbEGAJUnV2Fp09AzMGDZVOjGjh12GFqcj9920PZODMiZKeqtxUgsDMDfhhPsaU28/URxBbYHsPYc5CSS6KA1xBTum+OjLbpa9/B+ksx+poMr7v4gha+Rxo1+3R2gkjeExHilZ7shK2l6bmugJXKFKl+JcBWYZHh9Rtp82FsH2s7sGfN749G/m9S2mc/hGcHqGKN28rn/QeUeuGD4dOZD3s8+mBjdxUjy2GY+NuJeGqnvnnYKqigl1epubDSkTxUYwHc981G38I7bwHtZe4DLy0PTbcStr5VWm4HgSw/d2+6+S6uO1psqu6buWSV66CIfkXj6+beMAmu/E9CH3R1/oDYlUxB4YNrPQKIkdGXygTzY1j8=
env:
  matrix:
    secure: pO/C8j8Xz/i63amTZ/PqLBVQ6oUn7Pre29VlMr7cFAGJRIXw3P7Drm73Zml9IjD+U/tW93kuH/qJmliHYg3hGun/NksiSArpGxO9m4sq9dgq+InUr336tR2u3iPqI/HaSVYI42j61J65mvlagyA+Qt4DjralOuY0X9ysAlkzsV5uCwGBwjH4WN+ippCe6Lg1u6v3/LVRCckkp6tDaOtJe/5u3lWY7AlbM9VClWQbgYEoswRe9VlKfFzHEY6KIYRliiB/k4S3d7I3yReyGWTUQt4rDeEzQFWkKJK22YCBEGFT0uBBX1LCr2Tfrkd82Fk4p3sdPhI6v084qYcLPELEUeF9cdVJzG1L41Fi+Z8UqDxlaJg9p7m9yH/ge6V5/bbOrseLDufYc5otq/D7u8VNUb6SMFegJVBnepv0W3YYcghDLRGHOkiEFj08hAhsmkSV0fnzBSBvg/lqhJTn+k15xCdX2v74HegcqlZSF6zS2FjfUGQj2EjI6eWVkESmbIU5+qSviOz8DI4TeHvz/6gwZ/2GQuZ9PL39sbhHws1oAJvLbuLXYht03sO7oHWuTPbSCKcaKpEnOtxppkmGA3n4XEzkRHVm08A7gtBqBScHnMGtV/J+jbEKBUTbOWihybOq3Ij4h4mvDfUqf5E89kR6kTIyYzQ4vsObwdSeqfDbGcc=
